disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
included: # paths to include during linting. `--path` is ignored if present.
- GitExplorer
