# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GitExplorer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftLint'
  pod 'Alamofire'
  pod 'Kingfisher', '~> 6.0'
  
  target 'GitExplorerTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'GitExplorerUITests' do
    # Pods for testing
  end
  
end
